/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.minigoldengate;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.RandomAccessFile;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;



public class Login extends javax.swing.JFrame {
    FrontEnd frontend;
    BackOffice backoffice;
    boolean status1=false,status2=false;
     String host3,port_num3,user_name3 ,password3,database3;
     String host4,port_num4,user_name4 ,password4,database4;
     File f_fe = new File("Log_in_fe");
     File f_bo = new File("Log_in_bo");
     int ln;
    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        Host_TextField.setEnabled(false);
        Host2_TextField.setEnabled(false);
        PortNum_TextField.setEnabled(false);
        PortNum2_TextField.setEnabled(false);
        UserName_TextField.setEnabled(false);
        UserName2_TextField.setEnabled(false);
        Password_TextField.setEnabled(false);
        Password2_TextField.setEnabled(false);
        Schema_TextField.setEnabled(false);
        Schema2_TextField.setEnabled(false);
        SID_TextField.setEnabled(false);
        SID2_TextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     void createFolder_fe(){
        if(!f_fe.exists()){
            f_fe.mkdirs();
        }
    }
    
    void readFile_fe() throws FileNotFoundException{
        FileReader fr = new FileReader(f_fe+"\\log_in_fe.txt");
        System.out.println("file exists!");
        
    }
    
        void create_file_fe() throws IOException{
    
               File myObj = new File(f_fe+"\\log_in_fe.txt");
               if (myObj.createNewFile()) {
                 System.out.println("File created: " + myObj.getName());
                    } else {
                          PrintWriter writer = new PrintWriter(myObj);
                         writer.print("");
                         writer.close();
                     }
      
    }
    void create_file_bo() throws IOException{
    
               File myObj = new File(f_fe+"\\log_in_bo.txt");
              if (myObj.createNewFile()) {
                 System.out.println("File created: " + myObj.getName());
                    } else {
                         PrintWriter writer = new PrintWriter(myObj);
                         writer.print("");
                         writer.close();
                     }
    }
    void readFile_bo() throws FileNotFoundException{
        FileReader fr = new FileReader(f_fe+"\\log_in_bo.txt");
        System.out.println("file exists!");
        
    }
    void addData_fe(String host3,String port_num3,String user_name3 ,String password3,String database3) throws FileNotFoundException, IOException{
        
            RandomAccessFile raf = new RandomAccessFile(f_fe+"\\log_in_fe.txt", "rw");
            for(int i=0;i<ln;i++){
                raf.readLine();
            }
            //if condition added after video to have no lines on first entry
            if(ln>0){
            raf.writeBytes("\r\n");
            raf.writeBytes("\r\n");
            }
            raf.writeBytes("host_fe:"+host3+ "\r\n");
            raf.writeBytes("port_num_fe:"+port_num3+ "\r\n");
            raf.writeBytes("user_name_fe:"+user_name3+ "\r\n");
            raf.writeBytes("password_fe:"+password3+ "\r\n");
            raf.writeBytes("database_fe:"+database3);
        
        
    }
     void addData_bo(String host4,String port_num4,String user_name4 ,String password4,String database4) throws FileNotFoundException, IOException{
        
            RandomAccessFile raf = new RandomAccessFile(f_fe+"\\log_in_bo.txt", "rw");
            for(int i=0;i<ln;i++){
                raf.readLine();
            }
            //if condition added after video to have no lines on first entry
            if(ln>0){
            raf.writeBytes("\r\n");
            raf.writeBytes("\r\n");
            }
            raf.writeBytes("host_bo:"+host4+ "\r\n");
            raf.writeBytes("port_num_bo:"+port_num4+ "\r\n");
            raf.writeBytes("user_name_bo:"+user_name4+ "\r\n");
            raf.writeBytes("password_bo:"+password4+ "\r\n");
            raf.writeBytes("database_bo:"+database4);
        
        
    }
       void countLines_fe() throws FileNotFoundException, IOException{
       
            ln=0;
            RandomAccessFile raf = new RandomAccessFile(f_fe+"\\log_in_fe.txt", "rw");
            for(int i=0;raf.readLine()!=null;i++){
                ln++;
            }
            System.out.println("number of lines:"+ln);
       
        
    }
       void countLines_bo() throws FileNotFoundException, IOException{
       
            ln=0;
            RandomAccessFile raf = new RandomAccessFile(f_fe+"\\log_in_bo.txt", "rw");
            for(int i=0;raf.readLine()!=null;i++){
                ln++;
            }
            System.out.println("number of lines:"+ln);
       
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UserName_TextField = new javax.swing.JTextField();
        Host_TextField = new javax.swing.JTextField();
        PortNum_TextField = new javax.swing.JTextField();
        Password_TextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Host2_TextField = new javax.swing.JTextField();
        PortNum2_TextField = new javax.swing.JTextField();
        Password2_TextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        check_bo = new javax.swing.JCheckBox();
        check_fe = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        Schema_TextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Schema2_TextField = new javax.swing.JTextField();
        load_fe = new javax.swing.JButton();
        load_bo = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        clear_btn_bo = new javax.swing.JButton();
        UserName2_TextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SID_TextField = new javax.swing.JTextField();
        SID2_TextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniGoldenGate");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("BackOffice Connection");

        jLabel2.setText("Host             :");

        jLabel3.setText("Password     :");

        jLabel4.setText("User Name   :");

        jLabel5.setText("Port Number :");

        Host_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Host_TextFieldActionPerformed(evt);
            }
        });

        PortNum_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortNum_TextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Connect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("FrontEnd Connection");

        jSeparator.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setText("Host             :");

        jLabel8.setText("Port Number :");

        jLabel9.setText("User Name   :");

        jLabel10.setText("Password     :");

        Host2_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Host2_TextFieldActionPerformed(evt);
            }
        });

        PortNum2_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortNum2_TextFieldActionPerformed(evt);
            }
        });

        jButton2.setText("Connect");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        check_bo.setText("Save");
        check_bo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_boActionPerformed(evt);
            }
        });

        check_fe.setText("Save ");
        check_fe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_feActionPerformed(evt);
            }
        });

        jLabel11.setText("Schema        :");

        Schema_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Schema_TextFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Schema        :");

        load_fe.setText("Load");
        load_fe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_feActionPerformed(evt);
            }
        });

        load_bo.setText("Load");
        load_bo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_boActionPerformed(evt);
            }
        });

        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        clear_btn_bo.setText("Clear");
        clear_btn_bo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btn_boActionPerformed(evt);
            }
        });

        UserName2_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserName2_TextFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("SID               :");

        jLabel14.setText("SID               :");

        SID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SID_TextFieldActionPerformed(evt);
            }
        });

        SID2_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SID2_TextFieldActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select SQL server", "MySQL", "ORACLE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(check_fe))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PortNum_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(3, 3, 3))
                                    .addComponent(load_fe)
                                    .addComponent(jLabel13))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Host_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(UserName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(clear_btn))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(Password_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Schema_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(load_bo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clear_btn_bo)
                                .addGap(18, 18, 18)
                                .addComponent(check_bo))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(PortNum2_TextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(Host2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel12))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Schema2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Password2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UserName2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(SID2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel6)))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Host_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PortNum_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(UserName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Password_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Schema_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(check_fe)
                            .addComponent(load_fe)
                            .addComponent(clear_btn)
                            .addComponent(load_bo)
                            .addComponent(jButton2)
                            .addComponent(clear_btn_bo)
                            .addComponent(check_bo))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Host2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(PortNum2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(UserName2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(Password2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Schema2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SID2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Host_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Host_TextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Host_TextFieldActionPerformed

    private void PortNum_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortNum_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortNum_TextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String host = Host_TextField.getText();
        String port_num = PortNum_TextField.getText();
        String user_name = UserName_TextField.getText();
        String password = Password_TextField.getText();
        String Schema = Schema_TextField.getText();
        String SID = SID_TextField.getText();
        
        frontend = new FrontEnd();
        status1 = frontend.StartConnection(host, port_num, user_name, password, Schema, SID);
        
        if(status1 == true)JOptionPane.showMessageDialog(this, "Connection to FrontEnd Established...", "successful connection", INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(this, "Connection to FrontEnd Failed !", "warning", WARNING_MESSAGE);
         if(status1 == true && status2 == true){
            this.setVisible(false);
            try {
                TimeUnit.MILLISECONDS.sleep(100);
            } catch (InterruptedException ex) {
                ex.getMessage();
            }
           try {
                new MainPage(frontend, backoffice).setVisible(true);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Host2_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Host2_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Host2_TextFieldActionPerformed

    private void PortNum2_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortNum2_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortNum2_TextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String host2 = Host2_TextField.getText();
        String port_num2 = PortNum2_TextField.getText();
        String user_name2 = UserName2_TextField.getText();
        String password2 = Password2_TextField.getText();
        String Schema2 = Schema2_TextField.getText();
        String SID2 = SID2_TextField.getText();
        
        backoffice = new BackOffice();
        status2 = backoffice.StartConnection(host2, port_num2, user_name2, password2, Schema2, SID2);
        
        if(status2 == true)JOptionPane.showMessageDialog(this, "Connection to BackOffice Established...", "successful connection", INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(this, "Connection to BackOffice Failed !", "warning", WARNING_MESSAGE);
        
        if(status1==true && status2 == true){
            this.setVisible(false);
            try {
                TimeUnit.MILLISECONDS.sleep(200);
            } catch (InterruptedException ex) {
                ex.getMessage();
            }
             try {
                new MainPage(frontend, backoffice).setVisible(true);
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Schema_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Schema_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Schema_TextFieldActionPerformed

    private void check_boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_boActionPerformed
        try {
            host4 = Host2_TextField.getText();
            port_num4 = PortNum2_TextField.getText();
            user_name4 = UserName2_TextField.getText();
            password4 = Password2_TextField.getText();
            database4 = Schema2_TextField.getText();
            create_file_bo(); 
            readFile_bo();
            countLines_bo();
            addData_bo(host4,port_num4,user_name4,password4,database4);
            
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_check_boActionPerformed

    private void load_feActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_feActionPerformed
        try {
            RandomAccessFile raf = new RandomAccessFile(f_fe+"\\log_in_fe.txt", "rw");
            String line = raf.readLine();
            Host_TextField.setText(line.substring(8));
            PortNum_TextField.setText(raf.readLine().substring(12));
            UserName_TextField.setText(raf.readLine().substring(13));
            Password_TextField.setText(raf.readLine().substring(12));
            Schema_TextField.setText(raf.readLine().substring(12));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_load_feActionPerformed

    private void load_boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_boActionPerformed
           try {
            RandomAccessFile raf = new RandomAccessFile(f_fe+"\\log_in_bo.txt", "rw");
            String line = raf.readLine();
            Host2_TextField.setText(line.substring(8));
            PortNum2_TextField.setText(raf.readLine().substring(12));
            UserName2_TextField.setText(raf.readLine().substring(13));
            Password2_TextField.setText(raf.readLine().substring(12));
            Schema2_TextField.setText(raf.readLine().substring(12));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_load_boActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
            Host_TextField.setText("");
            PortNum_TextField.setText("");
            UserName_TextField.setText("");
            Password_TextField.setText("");
            Schema_TextField.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void clear_btn_boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn_boActionPerformed
            Host2_TextField.setText("");
            PortNum2_TextField.setText("");
            UserName2_TextField.setText("");
            Password2_TextField.setText("");
            Schema2_TextField.setText("");
    }//GEN-LAST:event_clear_btn_boActionPerformed

    private void UserName2_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserName2_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserName2_TextFieldActionPerformed

    private void check_feActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_feActionPerformed
        try {

            host3 = Host_TextField.getText();
            port_num3 = PortNum_TextField.getText();
            user_name3 = UserName_TextField.getText();
            password3 = Password_TextField.getText();
            database3 = Schema_TextField.getText();
            createFolder_fe();
            create_file_fe();
            readFile_fe();
            countLines_fe();
            addData_fe(host3,port_num3,user_name3,password3,database3);

        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_check_feActionPerformed

    private void SID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SID_TextFieldActionPerformed

    private void SID2_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SID2_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SID2_TextFieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Host_TextField.setEnabled(false);
        Host2_TextField.setEnabled(false);
        PortNum_TextField.setEnabled(false);
        PortNum2_TextField.setEnabled(false);
        UserName_TextField.setEnabled(false);
        UserName2_TextField.setEnabled(false);
        Password_TextField.setEnabled(false);
        Password2_TextField.setEnabled(false);
        Schema_TextField.setEnabled(false);
        Schema2_TextField.setEnabled(false);
        SID_TextField.setEnabled(false);
        SID2_TextField.setEnabled(false);
        
        int index = jComboBox1.getSelectedIndex();
        if(index != 0){
            Host_TextField.setEnabled(true);
            Host2_TextField.setEnabled(true);
            PortNum_TextField.setEnabled(true);
            PortNum2_TextField.setEnabled(true);
            UserName_TextField.setEnabled(true);
            UserName2_TextField.setEnabled(true);
            Password_TextField.setEnabled(true);
            Password2_TextField.setEnabled(true);
            Schema_TextField.setEnabled(true);
            Schema2_TextField.setEnabled(true);
            if(index == 2){
                SID_TextField.setEnabled(true);
                SID2_TextField.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Host2_TextField;
    private javax.swing.JTextField Host_TextField;
    private javax.swing.JTextField Password2_TextField;
    private javax.swing.JTextField Password_TextField;
    private javax.swing.JTextField PortNum2_TextField;
    private javax.swing.JTextField PortNum_TextField;
    private javax.swing.JTextField SID2_TextField;
    private javax.swing.JTextField SID_TextField;
    private javax.swing.JTextField Schema2_TextField;
    private javax.swing.JTextField Schema_TextField;
    private javax.swing.JTextField UserName2_TextField;
    private javax.swing.JTextField UserName_TextField;
    private javax.swing.JCheckBox check_bo;
    private javax.swing.JCheckBox check_fe;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton clear_btn_bo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JButton load_bo;
    private javax.swing.JButton load_fe;
    // End of variables declaration//GEN-END:variables
}
